{% set name = "jekyll-scholar" %}
{% set version = "7.1.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: d08722d88465eeed4baf6d8e52f66034526cb0dd25fb1b2f684eff2c79723fef

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-bibtex-ruby >=5.0,<6
    - rb-citeproc-ruby >=1.0,<2
    - rb-csl-styles >=1.0,<2
    - rb-jekyll >=4.0,<5

test:
  commands:
    - ruby -r {{ name|replace('-','/') }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Jekyll-Scholar is for all the academic bloggers out there.

  # The remaining entries in this section are optional, but recommended.
  description: |
    Jekyll-Scholar is for all the academic bloggers out there. It is a set of
    extensions for Jekyll the awesome, blog aware, static site generator; it
    formats your BibTeX bibliographies for the web using CSL citation styles
    and generally gives your blog posts citation super-powers.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/inukshuk/jekyll-scholar

extra:
  recipe-maintainers:
    - sodre
